name: "AUR Publish"
description: "Publish an AUR package"
author: loqusion
branding:
  color: green
  icon: upload
inputs:
  ssh_private_key:
    description: "The private SSH key to use to push the changes to AUR"
    required: true
  package_name:
    description: "AUR package name"
    default: ${{ github.event.repository.name }}
  git_username:
    description: "The username to use when creating the AUR repo commit"
    default: "AUR Release Action"
  git_email:
    description: "The email to use when creating the AUR repo commit"
    default: "github-action-bot@no-reply.com"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.package_name }} ${{ inputs.commit_username }} ${{ inputs.commit_email }} ${{ inputs.ssh_private_key }}
